basePath: /api
definitions:
  usercontroller.CreateProps:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  usercontroller.UpdatePorps:
    properties:
      name:
        type: string
      password:
        type: string
    required:
    - name
    - password
    type: object
  util.Response:
    properties:
      data: {}
      error: {}
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: umarbahabasi@gmail.com
    name: API Support
  description: This RESTFULL API users
  title: Swagger users go
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: get listing users with limit offset
      operationId: get-list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/util.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.Response'
      summary: get list users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: create user
      operationId: create
      parameters:
      - description: create new user return id
        in: body
        name: raw
        required: true
        schema:
          $ref: '#/definitions/usercontroller.CreateProps'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/util.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.Response'
      summary: create user
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: delete user
      operationId: delete
      parameters:
      - description: id user
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/util.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.Response'
      summary: delete user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: get oneing users with limit offset
      operationId: get-one
      parameters:
      - description: id user
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/util.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.Response'
      summary: get one users
      tags:
      - users
    put:
      consumes:
      - application/json
      description: update user
      operationId: update
      parameters:
      - description: id user
        in: path
        name: id
        required: true
        type: integer
      - description: update user return id
        in: body
        name: raw
        required: true
        schema:
          $ref: '#/definitions/usercontroller.UpdatePorps'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/util.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/util.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/util.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.Response'
      summary: update user
      tags:
      - users
swagger: "2.0"
